### ISSUE TITLE
fa-bars not responsive on home-page

### ISSUE THREAD

**Issue by gadfly361** [shakacode/shakacode.github.io#1]
In the mobile view of the homepage, when clicking the `fa-bars` the dropdown opens up (as expected); however, when you click the `fa-bars` again, the dropdown doesn't close :(

![image](https://cloud.githubusercontent.com/assets/8610039/11648697/e5083bae-9d2b-11e5-9ec1-3eb90b2badcf.png)

**Comment by justin808** [comment]
@rffaguiar When you get a chance, take a look at this.

@gadfly361, Thanks!
